### ISSUE TITLE
Crash when saving RDS

### ISSUE THREAD

**Issue by juddpatterson** [nationalparkservice/SET-viz#20]
After running the latest dashboard with Jim's sample data I can get to the point where it asks me to save the RDS, but then the dashboard crashes.

At first I wondered if it's related to these parsing errors that I noticed in the console:
![image](https://user-images.githubusercontent.com/50838982/93128513-9e0a6080-f69d-11ea-9fdf-b94b861b33fe.png)

I tried again with SFCN files in the 'Data_in' folder and I do not see the parsing errors, but I still get the same crash. Both file sets were working for me earlier today.

Don't you just love vague, broad bugs!

**Comment by ellenmonster** [comment]
Fixed
