### ISSUE TITLE
Suggestions for flags in data

### ISSUE THREAD

**Issue by ChesVerv** [nationalparkservice/SET-viz#39]
I was going through data and came across some that looked "off" as far as change (see CAHA11B last direction pin 5). It turns out that these have large deviations b/c there was a hole there at 2 of the readings. If this could either be outlined in the output or shown in the dox visible when the # is hovered over (both would be ideal). Please see word doc for suggestions.
[Git Flag Examples.docx](https://github.com/nationalparkservice/SET-viz/files/9854338/Git.Flag.Examples.docx)

**Comment by ellenmonster** [comment]
This should be addressed now with the option to simultaneously view actual pin height and change in pin height. When there are holes in the data the actual pin height will show as "N/A". Let me know if the fix doesn't sufficiently address your request
