### ISSUE TITLE
Map wish

### ISSUE THREAD

**Issue by ChesVerv** [nationalparkservice/SET-viz#40]
This may be more for an output dashboard rather than for the QA/QC dashboard but if we could get multiple sites on a map that would be really cool! I have some sites at TIMU and other places close together and it would be neat to see their pie charts on the same map.

**Comment by ellenmonster** [comment]
The maps (and all the other summaries) show one site at a time. The site is selected on the first page. This is to keep things manageable and to focus on QA/QC, rather than looking at patterns across sites. I agree, it would be a good idea for an output dashboard rather than the QA/QC.
