### ISSUE TITLE
Suggestion to help approving data

### ISSUE THREAD

**Issue by ChesVerv** [nationalparkservice/SET-viz#42]
I was working on approving data off of one of my easier parks (CAHA) and using the visualizer and the database simultaneously. What I do in this process is to look at large changes and double check the data in the database and it would be super helpful if the directions were labeled in the visualizer (either on the side or when you hover over a number). I have attached a screenshot of what I look for when I am approving data, In this shot I have circled a change that triggers me to go back and see if there was a not or if the data was wrong etc....Also in the same shot why are there zeros in some of the first read sections?

Enjoy!
[Visualizer suggestion.docx](https://github.com/nationalparkservice/SET-viz/files/9870883/Visualizer.suggestion.docx)

**Comment by wwrightuga** [comment]
@ChesVerv @ellenmonster  Ellen the field for the direction is in the SET Data view, SET_direction_azimuth. That's what Ches is asking for on the Y axis.

**Comment by ellenmonster** [comment]
@wwrightuga @ChesVerv This is just a response to the question of why there are zeros in some of the first read sections--for those two, there are duplicate records that differ only in pin_code (one says pin code is Hole, the duplicate record says pin code is Exclude from Analysis). This is the same issue that leads to the funny TIMU03 heat map (which I just sent a question about)

**Comment by ellenmonster** [comment]
Hi, I've modified the dashboard to address this request. Please "pull" the latest dashboard version to your computer (see GitHub instructions) to see the changes--you can post a new issue if the changes don't sufficiently address this request
