### ISSUE TITLE
Pie charts title cuts off with only one year of data

### ISSUE THREAD

**Issue by WendyWright** [nationalparkservice/SET-viz#44]
Adjust size on change in pin height >> pie charts so title fits

**Comment by ellenmonster** [comment]
Can you tell me which site this occurs with, so I can get a better sense of what I need to set minimum width to?

**Comment by ellenmonster** [comment]
Given all the calculations to get the dates (col names) and station labels to line up correctly with their respective pies, depending on the number of pies in the matrix and the margins and pie sizes I will probably just reduce the title font size if the number of data years is less some some amount--will need to play around with the offending data to see how best to format it

**Comment by ellenmonster** [comment]
Shortened the relevant plot heading considerably and reduced date size conditional on number of survey events. This should allow title and dates to show even with few surveys.
