### ISSUE TITLE
Show trend values on Hover for line plots

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#47]
Location - Pin Heights tab / Line Plots

After considering this a bit more, I now think that I would want these values displayed on the graphic somewhere.  Maybe in the legend to the right to keep the graphs from getting messy..

**Comment by ChesVerv** [comment]
I was just coming in here to comment on that, it would also be nice to see a cumulative line chart (perhaps in the public version)

**Comment by NPSlynch** [comment]
So the current line plots are for the Pin Heights tab are showing a line for each of the four directions (ABCD). At some point when this goes to the public I agree that we'd have some type of overall combined trend for each site.

**Comment by ellenmonster** [comment]
I'm going to hold off on providing any trend value until we address the issues that currently make statistical trend estimation questionable (things like not correcting the pin heights for pin lengths, so changes in the pin sets have not been accounted for)

**Comment by NPSlynch** [comment]
I am working to get the "Normalized Pin Data" working in the database exports so that you can properly display the heat maps and trends..
