### ISSUE TITLE
Left Side Panel Comments

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#51]
This is regarding this particular page and the mechanism for noting flags and alerts on the raw data.
Location: Pin Heights Tab / Heat Plots Tab

1) Put Park Name above SITE in this panel. I had this comment earlier

2) remove HEAT Plots tab name and other heat plot text on this page

3) Trying to figure out if there is a better way to organize the categories in this left panel....
I'm thinking there are four categories:
     1. DPL not accepted (Text red?)
     2. Notes - Event, vegetation, SET (yellow)
     3. Pin flag code/notes and Analysis flags (Orange)
     4. SET reader/Instrument changed.. (BLue box).

This is important info to present on this page. I NEVER use the analysis flags, so they have little meaning to me. The most important info for my data EVENT NOTES and SET NOTES.... For example, if I select the checkbox "Has event notes" nearly all of my cells have a blue box around them.

Not sure how to present these options... a cell can't have 2 fill colors at once...Can we something in the corner of the cell to indicate a note or flag?  We might want to discuss this as a group to decide on how to best present this info.

**Comment by ellenmonster** [comment]
Discuss during next meeting

**Comment by ellenmonster** [comment]
I don't know if we addressed these already or not. If not, let's discuss it with the other PI's just so we have agreement on it before I change anything. I think Chez uses the analysis flags, so they actually have meaning to him since this dashboard is for QA/QC and it helps him identify data to double-check. If is this issue is already resolved, let me know and I'll close it out--otherwise please put on agenda for meeting

**Comment by NPSlynch** [comment]
Chatted with Ches about the checkboxes on the left side and we're fine leaving them as is.... I tried to reorganize the order of the checkboxes.  It doesn't really matter if you don't change it!  As far as which are checked by default..... it's your call.  

1) DPL not accepted 
2) SET reader changed
3) SET instrument Changed
4) Pin Collection Changed
5) Event Note
6) Pin Flag/Note
7) Analysis Flag/Note
8) SET notes
9) Vegetation notes

**Comment by ellenmonster** [comment]
Reordered
