### ISSUE TITLE
SET raw pin height data 

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#52]
Location: Pin Heights Tab / Heat Plots Tab

This page shows SET arm directions (4 per SET) and the data from each of the 9 pins for every sampling event.

1) Each Group of 9 pins should be labeled on the page (M5-1A, M5-1B, M5-1C, etc...). Right now there are no labels describing the arm direction unless you hover over some data.

2) The 4 directions should start with A and go in order... B,C,D etc....  Right now the station I'm looking at (ASIS M5) starts with the B-direction first and goes BCDA.

3) I use ABCD which I'm assuming most of us use.... Maybe include the bearing too.

**Comment by NPSlynch** [comment]
This page is great.  I believe the SET arm directions for a station are being sorted based on the azimuth.  Would be better, in my opinion if they were sorted by ABCD. I'll check with Ches and Kevin

**Comment by NPSlynch** [comment]
Met with Kevin and Ches.... We agreed that this should have the direction and associated label (ABCD or 1234).

**Comment by ellenmonster** [comment]
Fixed
