### ISSUE TITLE
Heat Plots - Pie Charts - Maps

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#53]
1 - Heat plots - Look great - Need to give the arm directions on the screen and order them ABCD. 

Current heat plot is showing change values (T2-T1) for each sampling event. Might be nice to show this heat map 2 ways. 
    a) with actual raw pin data
    b) the change values (you are currently showing this)

This may help you catch a data entry error with the raw pin data....

Blue background color ="within expected range". This is not correct as we don't know the "Expected" range. Should say something like "no large changes".

I should NOT be seeing the Pie Chart Sliders on this tab! (left side panel)

2 - Pie charts 
Look fine though they are summarized to the Station. No arm directions.
I should NOT be seeing the Pie Chart Sliders on this tab! (left side panel)

3 - Maps
Look fine. Like the animation for each date!

**Comment by ellenmonster** [comment]
Fixed
