### ISSUE TITLE
Long data records not plotting correctly

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#56]
Pin Heights/Heat Plot tab

Raw data for a park like CACO goes back to 1998.  Some sites have over 40 sample events (CACO/NAUSET Marsh, CACO/Herring River).

The line plots are fine but the raw data (heat Plot) is not plotting properly. Data is very small and not all of the data is plotting!

**Comment by ellenmonster** [comment]
This one is sizing the heat map based on the first station # of cols. Need to size each individually.

**Comment by ellenmonster** [comment]
Wow! Can't believe it took all day to figure out a fix for this one. But it's fixed now! Thanks for finding this issue, Jim!

**Comment by NPSlynch** [comment]
Nice job Ellen... Thanks!
