### ISSUE TITLE
Big Picture Summary - Pin summary and marker summary cols should match better

### ISSUE THREAD

**Issue by ellenmonster** [nationalparkservice/SET-viz#58]
SET summary table does not have % validated, and has separate col for each DPL. DPL actually applies to the COMBINATION of SET and marker horizon data, so it's not clear why it's shown just with SET data.

**Comment by NPSlynch** [comment]
In my opinion, the number of records is not that informative. What's more informative is the number of sampling events which would work in these tabs. I do see the EVENT DATA tab but that's a mess to make sense of

**Comment by ellenmonster** [comment]
Done
