### ISSUE TITLE
Heat plots showing just raw SET pin heights--should color coding be removed, or should it reflect pin heights, or leave it as thresholds for change?

### ISSUE THREAD

**Issue by ellenmonster** [nationalparkservice/SET-viz#61]

**Comment by NPSlynch** [comment]
I like the color coding for both the raw pin heights and the changes.  Nice for seeing the big changes regardless if it's the pin height or the pin height change

**Comment by ellenmonster** [comment]
In our most recent conversation, I think Jim said the 'raw only' and 'change only' heat maps were redundant because we have the heat maps that show both simultaneously
