### ISSUE TITLE
Question for ecologists--survey dates may not match across stations, how should this be handled for heat maps?

### ISSUE THREAD

**Issue by ellenmonster** [nationalparkservice/SET-viz#71]
E.g., if Station A has data 2016-2022 and Station B has 2006-2022, should Station A have blank cells for 2016-2005 so the cols line up with Station B? Even when years match up, the actual survey dates may not--so should it not go by survey date but instead of survey event-within-year, e.g., 2016-1, 2016-2, 2017-1, 2017-2...   Seems that seasonal differences in survey dates should also be highlighted b/c the change btwn seasons may be expected to be greater than change btwn years for same month

**Comment by NPSlynch** [comment]
having all those blank cells would be a bit confusing.. Implying to me that there's a LOT of missing data.  Can you pass along an example showing this?

**Comment by ellenmonster** [comment]
No longer relevant. Heat maps have been changed to show stations separately.
