### ISSUE TITLE
Park Summary / Pin and MH summary page comments

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#76]
Jim Lynch Comments - 2/1/2023
1. **Number of Years column** - I thought this was the length of data record (Last year - First year) but this is actually the number of years with data. This is not very useful to me. I would prefer the full length of the data record. 
3. **Number of sampling events** - I would like to see a column with this number which is the total number of sampling events over the full record. I think this is more relevant for QA/QC than the current "Number of years of data."  I normally visit my SETs 2x per year so for a 10-year data record, I would have about 20 sampling events. But this is not always the case, and this would be useful to see this number.  For example, FIIS - Great Gun Site... GG1, GG2, GG3. There were a few times when I could not sample GG1 over the course of my data collection. This would show up as one or two less sampling events than with GG2 and GG3. These differences would prompt me to double check the data to confirm that the SET was actually not sampled. I can't tell that as readily with the "Current # of years of data" and the "Number of Records" Column (too much data in this one!).

**Comment by NPSlynch** [comment]
Ellen - Spoke to Kevin and Ches about the PARK SUMMARY page. They agree with 1 and 2 above.
1-Number of years = last sample - first sample
2- Number of Sampling events - 

We all agreed that "number of records" is not very useful. I think it is showing the total number of pin measurements... I would think that you could replace this column with number of sample events.

**Comment by ellenmonster** [comment]
Made the two requested changes. I did leave # of records in the subtable as a column, but in the main pin and MH tables I instead have '# of Service Yrs' (calc as last year minus first year of service) and '# of Sampling Events' instead of '# of Records'. Changes will be reflected in the next upload to GitHub
