### ISSUE TITLE
Label changes

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#77]
Ellen - Kevin, Ches and I spoke about this and agree.
1- Main menu at the top - Change "Pin Heights" to "SET data" 
2- Park Summary - Change "Pin Summary" to "SET summary"
3 - Pin Heights - Heat Plots - Each group of 9 pins should have the "Pipe Direction" shown on the page (left of the pin position?) to help us distinguish the 4 directions for a given pipe.  We know they are visible when hovering, but it would be nice to have them shown all the time. The 4 directions are sorted by the bearing (0 to 360) which doesn't always match the labels (a,b,c,d or 1,2,3,4), so it's helpful to see the labels on the screen.
4 - Marker Horizon Data - Heat Plots - Add the MH Name to the page like for the SET heat plots above.  They are visible with the hover but we'd like to see them listed on the page. I think they will always be sorted A, B,C, D etc. which is good.

**Comment by ellenmonster** [comment]
I think we fixed all these in my last meeting with you & JP, right?
