### ISSUE TITLE
New option for the SET Heat Plots

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#78]
Ellen - Kevin, Ches and I spoke about this and agree.

Pin Heights - Heat Plots

Items 1,2 and 3 are already there. Item 4 would be a new option:

1)	Pin Height – Shows just the pin value 
2)	Change in Pin Height - Shows only the interval change in SET pin heights from T1- T2, T2-T3, etc…
3)	Change and Pin Heights: Values in heatmap cells show the Interval change in pin heights from the previous event [actual pin heights are shown in brackets]
4)	NEW: Absolute change and Pin Heights - Values in heatmap cells are CHANGE in pin heights from the initial (Time zero) reading [actual pin heights are shown in brackets].

**Comment by ellenmonster** [comment]
Done. You'll see it in the next version uploaded to GitHub.
