### ISSUE TITLE
Hover Issues - MH - Heat plots

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#79]
Jim Lynch comment: Marker Horizon Data - Heat Plots

1 - Site = CACO/Blackfish Creek, COLO/M13: The hover box is clipped on the left side for some of the stations. 

2 -Site - COLO/M13: Should the hover always work on any cell? For COLO/M13 some of the cells did not pop-up when I hovered over them.

FYI - I could not get this to happen for the SET heat plots.

**Comment by ellenmonster** [comment]
Good catch! Now fixed. You should see it in the next dashboard version uploaded to GitHub.
