### ISSUE TITLE
Add caveat message that pin heights not corrected for pin length & heat map for change may reflect different change durations (# of days passed)

### ISSUE THREAD

**Issue by ellenmonster** [nationalparkservice/SET-viz#82]
This is esp. relevant for calculations of change in pin height btwn surveys or change from base pin height b/c we may be working with different pin sets--the warning text should be prominently displayed as figure/table caption or something else that will be exported with the image

**Comment by NPSlynch** [comment]
I agree.. Very important to account for this until we can get normalized values working it the exports (columns Q and R).

![image](https://github.com/nationalparkservice/SET-viz/assets/36487998/229a0cdd-f7b7-42ef-b73f-428dba5402e0)
