### ISSUE TITLE
Marker Horizon Data tab - Update summaries issue

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#83]
Marker horizon data/Heat plots: one of the checkboxes on the left side needs to be selected in order for it to update the summaries. If all of them are unselected and you hit "Update Summaries", nothing will happen.  You need to have at least one checkbox chosen in order for the "Update Summaries" to work.

SET pin data - heat map and line plots: This appears to be working for the SET Pin data. You CAN unselect the checkboxes and it does update the summaries.

**Comment by ellenmonster** [comment]
Fixed. Available in next push to GitHub
