### ISSUE TITLE
Later - SET Pin data considerations 

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#84]
At some point we will need to deal with the double read data since it's not displaying properly in its current form. One of the sets of pin data is not being displayed.  But if they were showing correctly, you'd have two sets of pin data for the same date and the heat map would look a mess. In the past, I would give the newer of the two sets of pin data a different date (add one day). That way they wouldn't overlap. maybe we can find a way to make this work in the dashboard in the future.

It will also be helpful when we get the normalized and pin elevation data working. This will result in three types of SET pin data.

1) SET pin data - raw - original readings from the field data
2) SET pin data - normalized - Pin data normalized to deal with changes in the pin length and receiver changes (raising up the receiver when updating it).
3) SET Pin data - elevation - This is SET Pin data converted to an orthometric height like NAVD88 (meters).

**Comment by ellenmonster** [comment]
Do you want to set up a meeting with you, me & JP to discuss options for showing this in the dashboard?

**Comment by NPSlynch** [comment]
I'm ok with that! Jim

**Comment by ellenmonster** [comment]
I sent a message to JP to find out if he can meet

**Comment by ellenmonster** [comment]
Per SET meeting, double reads should be shown as bold text and then on hover, show the double reader name and value

**Comment by ellenmonster** [comment]
Done
