### ISSUE TITLE
SET Data and Marker Data - Heat Plot tables - Changes to HOVER fields

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#88]
Would be nice to have some additional data appear when hovering over a cell when looking at the heat plot data.

New Fields to include for SET data:
1) SET_reader - Name of the person taking the measurements
2) Pin_collection - Name of the pin collection
3) pin_length_mm - Length of the pin

Changes to the Marker Horizon Data - 
1) established_date - Date the MH was established
2) core_type
3) core_condition = This field is already there under ALERTS!!.  This should NOT be an alert. Keep it but don't put it under ALERTS. 
4) core_notes
5) core_event_notes

Then a HOVER on SET or MH data would show this additional data in the pop-up.

Thanks!

Jim

**Comment by ellenmonster** [comment]
For MH, having core_condition under alerts allows the user to see the data highlighted for poor core conditions, which may be useful (I think) for identifying particular cores that are "on their way out" or sites where perhaps MH data may be less reliable--without having to hover on the individual cell to identify which may have poor core condition. For now I will add it to hover but also keep it as an Alert option. If all PIs agree it should be removed from Alert options, though, I will do so

**Comment by NPSlynch** [comment]
I think that will work... It would be nice to show the data for these plots in some fashion that will allow you to see that a particular data point is only the average of 1 number!

**Comment by ellenmonster** [comment]
Hmmm...not sure what "average of 1 number" means

**Comment by NPSlynch** [comment]
Sorry - I am referring to the plots for a particular site (COLO M5). COLO M5 would have 3 stations (1,2,3) and each station has 3 MH plots around it (A,B,C). I believe you are creating plots for each station (A, B and C). I don't believe you are creating an overall, plot for the site (Avg of all 9 plots).  I'm referring to the situation where you are averaging many plots but when they start disappearing, there are less and less numbers going into that average. Sorry to confuse you. Work on what you have going and I'll take a look. Please let me know when I can do a PULL.

**Comment by ellenmonster** [comment]
Correct, there is no averaging many plots, as that would cause problems when the MH plots change so that from one survey event to the next the underlying MH plots may be different. Each station will be plotted, so it will be obvious when one station "expires" and a new station is added.

**Comment by ellenmonster** [comment]
Fixed in the next iteration that will be uploaded
