### ISSUE TITLE
SET data - Standardized data and Elevation Data now working

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#89]
FYI - Right now your SET line plots are using the raw pin data. We have started to get these other versions of the data working (ASIS and GATE). There three types of SET pin data available coming from the SET database

1) SET Pin data - Raw SET pin height data (Col: P, Field: pin_height_mm) - This is what you've been working with.

2) Standardized pin data - Pin data normalized based on the below info.
    A. Raw SET pin height data (Col: P, Field: pin_height_mm)
    B. Pin length (Col AE, Field: pin_length_mm)
    C. SET offset - This is the distance from the top of the SET receiver to the top of the horizontal arm of the SET. 
                            This is a fixed value of about 393mm (Col:AH, Field: SET_offset_mm)
     Formula - Right now the formula is:  Std Pin Height (mm) = C+A-B. This gives a NEGATIVE number for now. 
                      Eventually they will add 1000 to this formula to make the values positive. 

3) Soil Elevation (Col: R, Field: soil_elev_m)
    This is another way to present the pin data as an orthometric height (NAVD88, meters). Based on the below info from the DB.
     D. Elevation of the top of the SET receiver in meters (This is in the DB but not in the export! It should be.)
    
      Formula - The formula is:  Soil Elevation (m)=  D+C+A-B. Note that you'd need to make sure all fields are in 
                       meters for this column of data.

Note that the math for the two are already in the export so you shouldn't have to do any calculations on your end.

So eventually - The line plots could be based on these other two types of data.

Get it touch if you have questions.

Jim

**Comment by ellenmonster** [comment]
In the user selection, the options then should be: 
- Raw data (using pin_height_mm column)
- Standardized data (DO YOU KNOW THE COLUMN NAME FOR THIS ONE?)
- Orthometric height (using soil_elev_m column)

Am I getting the names and columns correct?

**Comment by ellenmonster** [comment]
Question for Jimsky!

**Comment by NPSlynch** [comment]
That is correct for the SET data!

**Comment by NPSlynch** [comment]
Pin Height = pin_height_mm
Standardized = standardized_soil_elev_mm
Orthometric = soil_elev_m

**Comment by ellenmonster** [comment]
What is the data type for 'soil_elev_m'? I assume it's a numeric decimal, not an integer--right? Are there other data columns that should be decimal and not integer?

**Comment by NPSlynch** [comment]
Yes - It's the elevation of the marsh surface in meters. Not an integer

**Comment by ellenmonster** [comment]
Done! Took a lot longer than expected :(
